### ISSUE TITLE
how to remove the 3'   5' adapeters or the ployA tail form  the postprocessing sequences

### ISSUE THREAD

**Issue by wlhCNU** [rvolden/C3POa#8] opened 2019-04-23 03:42 UTC
Hi,
When get the postprocessing sequences,what I need to de next is to remove the 3' and 5' adapeters and the ployA tail. Do you have a good implementation or software to do this ? Thanks.

**Comment by rvolden** [comment] 2019-04-24 18:15
Duplicate of [#7](https://github.com/rvolden/C3POa/issues/7)

**Closed as completed** 2019-04-24 18:15 UTC
